input {
  beats {
    port => 5044
  }
}

filter {
  # 추후 결제 로그나 DB 감사 로그를 정제할 때 여기에 필터를 추가합니다.
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "payguard-logs-%{+YYYY.MM.dd}"
  }
  # 디버깅을 위해 터미널에도 로그를 찍어줍니다.
  stdout { codec => rubydebug }
}
